### ISSUE TITLE
Не реализована поддержка TLS

### ISSUE THREAD

**Issue by uyfan** [BITERP/PinkRabbitMQ#19]
В компоненте не реализована поддержка TLS.
Соединение с сервером через защищенное подключение (например, порт 5671) возвращает ошибку "Wrong login, password or vhost".

**Comment by ripreal** [comment]
Такую поддержку возможно реализовать, если найдется желающие это сделать, хотя с ней придется повоозится для Windows платформы.

**Comment by aliczin** [comment]
@ripreal у вас тогда CloudAMQP работать никогда не будет. Точнее будет но через хитрый ход с Shovel/Federation

CloudAMQP - сейчас по умолчанию использует протокол `amqpS://` на 443 порту
