### ISSUE TITLE
Соединение с сервером RAbbitMQ разрывается при простое

### ISSUE THREAD

**Issue by ripreal** [BITERP/PinkRabbitMQ#22]
Есть предположение, что в linux версии компоненты после вызовыа метода Connect при бездействии (отсутствия трафика) происходит автоматический разрыв соединения. Нужно проверить и при необходимости исправить. Источник: https://github.com/BITERP/PinkRabbitMQ/issues/21

**Comment by antonwantstosleep** [comment]
Кроме того, если цикл чтения продолжает выполняться, когда соединение уже разорвалось:
- метод BasicConsumeMessage возвращает Ложь и переопределяет outdata = "", messageTag = 3
- метод BasicAck вызывает ошибку "Error. RabbitMQ channel is not in usable state"
