### ISSUE TITLE
Для сборки Windows версии компоненты в репе не хватает заголовочных файлов Poco/Net

### ISSUE THREAD

**Issue by antonwantstosleep** [BITERP/PinkRabbitMQ#25]
При попытке собрать PinkRabbitMQWindows (например Release - x64) в VS (Сборка -> Собрать решение) возникают ошибки:
```
1>C:\Distr\PinkRabbitMQ\PinkRabbitMQWindows\NativeAPI\RabbitMQClient.cpp(6,10): fatal error C1083: Не удается открыть файл включение: Poco/Net/NetException.h: No such file or directory
1>C:\Distr\PinkRabbitMQ\PinkRabbitMQWindows\NativeAPI\SimplePocoHandler.cpp(7,10): fatal error C1083: Не удается открыть файл включение: Poco/Net/StreamSocket.h: No such file or directory
```
Для исправления ошибки потребовалось скачать https://github.com/pocoproject/poco/archive/poco-1.9.0-release.zip и скопировать оттуда каталог Net в PinkRabbitMQWindows\libs\poco-poco-1.9.0-release\Net.

З.Ы. Сначала скачал poco 1.10.1 (крайний) и долго не мог понять, почему у меня компонента крашится на методе connect...

**Comment by ripreal** [comment]
Можно положить их в нужное место в репо. Тогда нужно будет еще скорректировать gitignore файл. Я не возражаю. По поводу версии poco в ридми в разделе про установку написано, что используется версия 1.9.0. Но я не против того, что написать про это более очевидно.

**Comment by ripreal** [comment]
@antonwantstosleep Спасибо за ценные замечания. Поправил. Причина была в ошибке в гитигноре, который случайно исключить необходимо хедеры
