### ISSUE TITLE
Не работает метод GetPriority

### ISSUE THREAD

**Issue by kastortroy2006** [BITERP/PinkRabbitMQ#27]
При получении сообщения метод GetPriority возвращает неопределено.
Если получить сообщение через веб интерфейс, свойства сообщения:
Properties	
priority:	8
delivery_mode:	2

**Comment by ripreal** [comment]
Метод не реализован до конца. Не хватает куска конвертации переменной priority  в tVariant pvarRetValue.

```
bool CAddInNative::getPriority(tVariant* pvarRetValue, tVariant* paParams) {
	int priority = client->getPriority();

	return true;
}
```
https://github.com/BITERP/PinkRabbitMQ/blob/master/PinkRabbitMQWindows/NativeAPI/CAddInNative.cpp

**Comment by ripreal** [comment]
@kastortroy2006 Ошибка исправлена в мастере и запланирвоана на релиз 1.9
