### ISSUE TITLE
Ошибка при сборке компоненты для Linux

### ISSUE THREAD

**Issue by YPermitin** [BITERP/PinkRabbitMQ#29]
При сборке проекта "PinkRabbitMQLinux" возникает ошибка:

Ошибка		openssl/ssl.h: No such file or directory
   19 | #include <openssl/ssl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.	PinkRabbitMQLinux	
\PinkRabbitMQLinux\src\amqp\include\amqpcpp\linux_tcp\tcpparent.h

Попытка сборки была под Win 10 с помощью Visual Studio 2019 + WSL.

Какую версию библиотеки openssl нужно добавить?
Можно ли это сделать непосредственно в репозитории?

**Comment by ripreal** [comment]
@YPermitin Все необходимые заголовки до единого включены в репозиторий. Проблема в другом. Сборка выполняется непосредственно на линуксовой машине, даже если разработка идет из под Windows. Необходимо на машине установить полноценный ssl сервер. Вместе с ними будут установлены и openssl/ssl.h  Как показывает опыт, лучше всего использовать не WSL а обычную линукс машину.

**Comment by YPermitin** [comment]
@ripreal все понял.

Ок, благодарю!
