### ISSUE TITLE
Компонента зависает, если пытается подключиться к порту, которого не существует на сервере. 

### ISSUE THREAD

**Issue by ripreal** [BITERP/PinkRabbitMQ#3]
Воспроизведение
1. Выполнить метод Connect компоненты, заполнив все параметры верно за исключением порта

**Comment by MinimaJack** [comment]
Возможные причины:

https://github.com/BITERP/PinkRabbitMQ/blob/7cba0ac5b4b05d5a94dbf30f7b7f5525004ac2ca/NativeAPI/SimplePocoHandler.cpp#L87-L93

Ожидает соединения так как нет таймаута
```
m_impl->socket.connect(address); <-- добавить таймаут 
```
Возможно добавить флаг TCP_NODELAY - для уменьшения latency
```
m_impl->socket.setNoDelay(true); 
```

**Comment by ripreal** [comment]
Спасибо за идею. Если не указан таймаут, то используется дефолтный таймаут в 20 сек. Так что причина не в этом. а неправильной обработке исключения TimeoutException. Собствено сейчас проверил - ошибка у меня на версии компоненты 1.2. не воспроизводится. НА более ранних версиях воспроизводилась

**Comment by ripreal** [comment]
Про флаг TCP_NODELAY  почитал https://thoughts.t37.net/nginx-optimization-understanding-sendfile-tcp-nodelay-and-tcp-nopush-c55cdd276765. 

Это правда не связано с проблемой

**Comment by MinimaJack** [comment]
@ripreal что то не видно где указан и используется дефолтный таймаут...в прекомпиленых либах?

**Comment by ripreal** [comment]
@MinimaJack  Да, в хедерах этого нет.

**Comment by ripreal** [comment]
Проверил. ошибка не воспроизводится с версии 1.2. Дефолтный таймаут соединения равен 20 секундам. Его можно перепутать с зависанием.

**Comment by ripreal** [comment]
Поняли в чем еще одна причина "зависания" компоненты. Если у кролика заканчивается оперативная память, то он не разывает существующие соединения, а "завешивает" т.е. инчего по ним не отвечает, а ждет когда у него память освободится. По видимому это и произошло при обмене с рабочей ERP (вчера @shock писал), соотвтесвенно от компоненты ожидается, что:
- даже если сам севрер кролика "зависил" соединение, то по таймауту сама компонента его прервет (не важно при отправке или при получении соединение зависло)
