### ISSUE TITLE
Ошибка при отправке методом BasicPublish

### ISSUE THREAD

**Issue by kastortroy2006** [BITERP/PinkRabbitMQ#30]
Отправляю сообщение. Размер сообщения 17.1 Мб.
Исключения не происходит.
Но в очереди сообщения не появляется.

Уменьшил сообщение до 10 Мб, отправилось и появилось.

Есть какие-то ограничения по размеру сообщения? Или в методе зашит таймаут ожидания?

**Comment by ripreal** [comment]
@kastortroy2006  Спасибо - это критическая ошибка. Все данные отправляются порциями по 8 мб и нет специальных лимитов на размер файлов. Проблема заключалась в том, что TCP слой работал в асинронной режиме и при большом количестве аллокаций буфера очередная 8-мегабайтая порция данных просто не ждала отправки предыдущей порции и в какой-то момент эти порциями могли пересечься и возникнуть повреждение памяти. Чем больше объем данны - тем вероятнее возникновение этой ошибки. 

Ошибка побеждена, сегодня будет выпущен новый релиз 1.9.
