### ISSUE TITLE
BasicPublish никак не реагирует на отсутствие прав записи по ключу маршрутизации

### ISSUE THREAD

**Issue by oldym** [BITERP/PinkRabbitMQ#31]
Если у пользователя, под которым произведено подключение, нет права публикации сообщений с определенным ключом маршрутизации, то метод **BasicPublish** не вызывает исключения, просто сообщение не будет опубликовано. Это очень затрудняет поиск проблемы, когда обмены перестают работать

**Comment by ripreal** [comment]
Это особенность реализациии. Отправка сообщений в компоненте до версии 1.9 включительно является асинхронной, т.к. протокол AMQP поддерживает возможность не ждать подтверждения доставки сообщения на сервере, чем мы и пользуемся.  В компоненте 1.10 эта логика возможно будет изменена на синхронную, если удастся достичь хотя бы отправки в несколько сотен сообщений в секунду в синхронной логике

**Comment by oldym** [comment]
> Это особенность реализациии. Отправка сообщений в компоненте до версии 1.9 включительно является асинхронной, т.к. протокол AMQP поддерживает возможность не ждать подтверждения доставки сообщения на сервере, чем мы и пользуемся. В компоненте 1.10 эта логика возможно будет изменена на синхронную, если удастся достичь хотя бы отправки в несколько сотен сообщений в секунду в синхронной логике

А как сейчас тогда убеждаться в том, что сообщение отправлено?

**Comment by ripreal** [comment]
"Обычно отправка сообщений не требует подтверждения и RabbitMQ не отправляет подтверждения о доставке." (https://github.com/CopernicaMarketingSoftware/AMQP-CPP)

 В нашем случае эта ситуация усугубляется невысокой корости отправки в 30 сообщений в секунду, поэтому никак
