### ISSUE TITLE
Проблемы подключения по SSL, подключения в Linux, компиляции проекта

### ISSUE THREAD

**Issue by akopylov-rdv** [BITERP/PinkRabbitMQ#42]
Столкнулся с рядом проблем при попытке использования компоненты:
1. **В windows** (Win10x64, 1C:8.3.17x32), не работает защищенное соединение, при вызове метода _connect_ компонента возвращает ошибку (get last error): **_Timeout_**. Ошибка вылетает мгновенно, без ожидания.
![PinkRabbitMQ_timout_error](https://user-images.githubusercontent.com/52494681/107340817-3c74e380-6acf-11eb-9711-bfc8a4157f59.png)
Не защищенное соединение - **работает**.
2. **В linux** не получилось подключиться к серверу RabbitMQ не по SSL/не без SSL. Linux x64 (Ubuntu 20 и 18), платформа 1C x64 (8.3.16, 8.3.17). Пакеты **_libssl libjsoncpp libevent_** установлены, но не исключена проблема с версиями пакетов.
- На актуальной сборке выпадает с ошибкой во время подключения компоненты
![PinkRabbitMQ_installed_linux_packages](https://user-images.githubusercontent.com/52494681/107340810-3aab2000-6acf-11eb-915c-a1527949ba91.png)
- На релизах 1.8, 1.9 при вызове метода connect() с ошибкой: **_RabbitMQ channel is not in usable state_**. Сетевые проблемы исключены, т.к. с использованием модуля pika (python) получается подключиться по защищенному и незащищенному протоколам.
![PinkRabbitMQ_not_usable_error](https://user-images.githubusercontent.com/52494681/107340813-3bdc4d00-6acf-11eb-992d-94dbcf38addb.png)
3. **Не компилируется** актуальный проект в репозитории (по инструкции):
- Если компилировать только исходники из его репозитория, то не находились хедеры из компоненты _poco_
- Скачал исходники _ampqccp_ и _poco_ свежие, они собрались без ошибок, перелинковал на эти пересобранные библиотеки, но при сборке компоненты появились ошибка уровня кода: про состав параметров методов. Похоже, что-то изменилось во внешних проектах.

**Comment by ripreal** [comment]
@akopylov-rdv Можно привести 1с-ый код для установления соединения? Какой порт используется?

**Comment by ipalenov** [comment]
@akopylov-rdv В linux распакуйте компоненту и выполните команду `ldd PinkRabbitMQLinuxLin64.so`.

**Comment by akopylov-rdv** [comment]
> @akopylov-rdv Можно привести 1с-ый код для установления соединения? Какой порт используется?
Порты используются нестандартные 4273, 4274 c SSL
![image](https://user-images.githubusercontent.com/52494681/107486767-7a890a80-6b96-11eb-99ca-79583db9e55c.png)
Используемый код в обработке ИнтеграцияRabbitMQ
[rabbitmq-kaa.cf.zip](https://github.com/BITERP/PinkRabbitMQ/files/5956955/rabbitmq-kaa.cf.zip)

**Comment by akopylov-rdv** [comment]
> @akopylov-rdv В linux распакуйте компоненту и выполните команду `ldd PinkRabbitMQLinuxLin64.so`.

@ipalenov 
![image](https://user-images.githubusercontent.com/52494681/107489751-0c464700-6b9a-11eb-9a1e-1119ee115bad.png)

**Comment by ripreal** [comment]
@akopylov-rdv Лучше вмест ообработки напишите как вызываете метод Connect в компоненте? Какие передаете параметры?

**Comment by akopylov-rdv** [comment]
> @akopylov-rdv Лучше вмест ообработки напишите как вызываете метод Connect в компоненте? Какие передаете параметры?

![image](https://user-images.githubusercontent.com/52494681/107504936-0e65d100-6bad-11eb-81d2-e69ab927bd02.png)

**Comment by Begemoth2** [comment]
> > @akopylov-rdv Лучше вмест ообработки напишите как вызываете метод Connect в компоненте? Какие передаете параметры?
> 
> В случае с windows
> 
> * если **Порт** = 4274 и **ЗащищенноеСоединение** = Истина, то соединение НЕ проходит - Ошибка: **_Timeout_**

Ну по этому коду нам сложно понять в чем проблема :-)

Мы сейчас используем эту версию компоненты c защищенным соединением с кроликом на https://www.cloudamqp.com/, проблем вроде нет. Код в 1С примерно такой же как у вас.

Попробуйте сделать бесплатный инстанс на https://www.cloudamqp.com/ и подключиться с защищенным соединением к нему (обратите внимание, что там другой порт)
Попробуйте подключиться к вашему кролику по защищенному соединению не через компоненту, а через какую-либо стороннюю программу (чтобы убедиться что защищенное соединение в принципе у вас в кролике работает, порт открыт, нет проблем с сертификатами)

**Comment by akopylov-rdv** [comment]
@Begemoth2 
1. Через другую программу подключаюсь без проблем (Python Pika)
2. А какой-код ещё хотите увидеть?) Там только один метод, странно ожидать чего-то больше, если проблема в подключении
3. Компонента под Linux вообще у меня никак не заработает, даже по незащищенному, и даже не подключается как компонента (см. выше). Если бы подключилась по незащищенному каналу, это уже было бы здорово, можно было бы через защищенный тоннель протащить.
4. https://www.cloudamqp.com/ - проверю вернусь с обратной связью

**Comment by ripreal** [comment]
@akopylov-rdv А версия компоненты 1.9. бекз защищенного соединения у Вас работает на линуксе?

**Comment by akopylov-rdv** [comment]
@ripreal 

`На релизах 1.8, 1.9 при вызове метода connect() с ошибкой: RabbitMQ channel is not in usable state. Сетевые проблемы исключены, т.к. с использованием модуля pika (python) получается подключиться по защищенному и незащищенному протоколам.`

**Comment by akopylov-rdv** [comment]
@Begemoth2  @ripreal 
С облачным ребитом и виндовой компонентой тоже самое, без SSL - работает, c SSL - нет, ошибка та же: timeout

https://user-images.githubusercontent.com/52494681/107620588-fd2ccb00-6c65-11eb-8122-b7027ab9d344.mp4

**Comment by akopylov-rdv** [comment]
Для ошибки таймаута, слишком быстро ответ происходит, может где-то нужно параметр таймаут > 0 указать

**Comment by ripreal** [comment]
Возможно у Вас кривая сборка 1.10. Вот собрал тестовую конфу с одной кнопкой Connect и подключением к облачному раббиту через amqps. Она у меня работает. https://yadi.sk/d/Vxu51Aoqos9OCw Проверяйте.

**Comment by akopylov-rdv** [comment]
@ripreal
Работает подключение SSL под windows с **_x64_** платформой, похоже проблема с компонентой для **_x32_** разрядной платформы.
К НЕоблачному ребиту получилось подключиться с SSL после того как в конфиге закомментировал проверку SSL цепочки сертификатов:

> #ssl_options.verify     = verify_peer

Возможно, что-то не так работает с хранилищем сертификатов

Под Linux компонента не подключается (_ПодключитьВнешнююКомпоненту_).

**Comment by Begemoth2** [comment]
> Работает подключение SSL под windows с **_x64_** платформой, похоже проблема с компонентой для **_x32_** разрядной платформы.
Спасибо за информацию. Проверим у себя на x86, если найдем ошибку исправим (но не раньше завтра)

> К НЕоблачному ребиту получилось подключиться с SSL после того как в конфиге закомментировал проверку SSL цепочки сертификатов:
> > #ssl_options.verify     = verify_peer
А где именно закомментировали эту строчку?
Т.е. правильно я понимаю, что это какое-то стороннее приложение на openssl, которое с проверкой сертификатов не работало с вашим внутреннем кроликом, а без проверки работало?

Правильно я понимаю, что вам в проверка подлинности сертификата в компоненте нужна, по этому нужно найти место/способ как зарегистрировать его в виндовс так, чтобы его видела компонента (также, как видит для облачного кролика)?

> Под Linux компонента не подключается (_ПодключитьВнешнююКомпоненту_).
Для линукса пока расследовать не планируем, т.к. в данный момент не планируем использовать данную версию компоненты для Линукс. Скорее всего проблема с зависимостями, т.е. нужно попробовать собрать все зависимости статически внутрь компоненты.

**Comment by akopylov-rdv** [comment]
@Begemoth2 
Планируем использовать компоненту только под Linux. 
Если не будет работать SSL, то можно найти временные решения, до тех пор, пока не станет работать.

**Comment by Begemoth2** [comment]
@akopylov-rdv 

1. Мы проверили работу с ssl на x86 под windows (т.е. взяли 32битную платформу под 64 битной windows). У нас проблемы не воспроизвелась
2. Мы уточним документацию по компоненте, сейчас
- компонента не передает сой сертификат в RabbitMQ при подключении по ssl, соответственно на сервере RabbitMQ нужно выставить настройки, чтобы не требовать проверку клиентского сертификата
- компонента проверяет серверный сертификат по данным операционной системы, где работает
т.е. только уточним документацию, пока ничего тут дорабатывать не планируем
3. По работе в Linux попробуем за ограниченное время разобраться, если получится - исправим,  если не получится, напишем в ограничения

**Comment by Begemoth2** [comment]
@akopylov-rdv Мы немного поразбирались с линуксом,  причина проблемы в том, что  в 1с лежит своя версия libstdc++. версии 6.7. И все библиотеки, юзающие фичи из версий выше, грузиться не будут. Т.е. если мы собираем нашу либу под libstdc++ 6.7, то она грузится, но системная openssl.so не грузится, ибо она собрана под системную libstdc++

Т.е. нормальным решением проблемы будет собрать компоненту со статическими библиотеками (т.е. все библиотеки нужных версий засунуть в компоненту), но пока мы это делать не планируем.

Есть способ обхода, если у вас используется ubuntu16/debian8 то вы можете сами попробовать собрать компоненту по инструкции из readme, т.к. в этих ОС системная libstdc++ ниже 6.7, то должно собраться и работать (но мы не уверены, сами не проверяли)

**Comment by Begemoth2** [comment]
@akopylov-rdv Мы собрали релиз компоненты для линукса (все библиотеки встроили внутрь компоненты) https://share.bit-erp.ru/public/file/szZvAWe-sUWVROBFbS-lQg/PinkRabbitMQ_v1.10_7.zip
Прошу проверить, работает ли у вас и написать

**Comment by akopylov-rdv** [comment]
@Begemoth2  
Компонента v1.10.7 подключается:
- c SSL
- без SSL
- с включенным параметром `ssl_options.verify = verify_peer` в конфигурации Rabbit MQ.

Буду пробовать работать с компонентой.
Это задачу можно закрывать, если будут ещё вопросы, то отдельно напишу.

Спасибо!

**Comment by ipalenov** [comment]
@akopylov-rdv 
Скажите, имеется ли у Вас возможность протестировать компоненту, собранную на GutHub Actions?
https://github.com/BITERP/PinkRabbitMQ/suites/2709752247/artifacts/59728198
