### ISSUE TITLE
Добавить возможность установить свойство app_id в компоненте

### ISSUE THREAD

**Issue by korableg** [BITERP/PinkRabbitMQ#7]
Для идентификации Базы 1С необходимо иметь возможность установить в данное свойство строку подключения.
В RabbitMQ данное свойство присутствует в списке:
![изображение](https://user-images.githubusercontent.com/29011926/63747712-fd9aa000-c8d1-11e9-8959-4f8034db4349.png)
В компоненте его нет:
![изображение](https://user-images.githubusercontent.com/29011926/63747813-320e5c00-c8d2-11e9-9007-99796ed3f1d2.png)

**Comment by korableg** [comment]
Для идентификации Базы 1С необходимо иметь возможность установить в данное свойство строку подключения.

**Comment by ripreal** [comment]
Сделано
