### ISSUE TITLE
Добавить поддержку всех метаданных сообщения RAbbitMQ

### ISSUE THREAD

**Issue by ripreal** [BITERP/PinkRabbitMQ#8]
В RabbitMQ есть набор свойств, передаваемых вместе с сообщением:
appID
messageID
typeName
correlationID
ContentEncoding
ContentType
UserID
ClusterID
Expiration
ReplyTo

Нужно добавить эти свойства в компоненту,, чтобы можно было их записывать / читать при обмене сообшениями

**Comment by VolAll** [comment]
Подскажите для чего нужны эти свойства и как с ними работать?

**Comment by ripreal** [comment]
Это специальные метаданные сообщения предусмотренные протоколом, влияющие на разное. https://www.rabbitmq.com/releases/rabbitmq-dotnet-client/v3.2.4/rabbitmq-dotnet-client-3.2.4-client-htmldoc/html/type-RabbitMQ.Client.IBasicProperties.html Если нет понимания, то лучше их не трогать

Как их использовать:
```
Компонента.appID = "Мой АП ид";
....
// ОТПРАВЛЯЕМ СООБЩЕНИЕ
....
// ПОЛУЧАЕМ СООБЩЕНИЕ
....
AppId = Компонента.appID;
Сообщить(AppId); // Мой АП ид"
```

**Comment by VolAll** [comment]
спасибо в телеге Nikita Gryzlov про это же сказал.
в документации этой информации не хватает.
