### ISSUE TITLE
Как узнать ответ Кролика на отправку сообщения в очередь?

### ISSUE THREAD

**Issue by johnnyshut** [BITERP/PinkRabbitMQ#91]
Правильно ли я понимаю, что используя метод "BasicPublish - Отправить сообщение" я не могу проверить на стороне 1С отправилось ли сообщения или нет? 
Например: я указал в отправке не существующий routingKey, в таком случаи в 1С я не получу ничего в ответ и метод не упадет в исключение. Очередь я не создаю в 1С. 
Как тогда отслеживать отправку?

**Comment by kuzyara** [comment]
Проверять наличие routingKey?

Похоже вы не храните конфигурацию в виде кода, поэтому не можете отследить изменения биндингов, поэтому и проблемы с несуществующими ключами маршрутизации.

Заведите единую точку внесения изменений (репозиторий) для управления своим кроликом через код 1с - тогда ваша проблема сама исчезнет.

![image](https://user-images.githubusercontent.com/2604430/217158670-7ffd70bf-c48d-4de3-887e-e5315044a972.png)

**Comment by kuzyara** [comment]
Вот как это реализовано в dotnet: 
https://stackoverflow.com/questions/72535226/how-to-set-mandatory-flag-on-rabbitmq-message

Если бы это свойство было реализовано и в нашей компоненте, то его использование выглядело бы так:
```bsl
Клиент.mandatory = true;
Клиент.BasicPublish("exchangeName","routingKey", ТелоСообщения);
```


https://stackoverflow.com/questions/65134452/how-to-handle-unknown-invalid-binding-routing-key-values-in-rabbitmq

А пока никак получается
